#!/bin/bash
python="$VIRTUAL_ENV/bin/python"
graphite_install_dir="$VIRTUAL_ENV"
graphite_version="origin/0.9.x"
carbon_version="origin/0.9.x"
stage_dir="$start_dir/tmp"

# Activate virtualenv
source $VIRTUAL_ENV/bin/activate

mkdir $stage_dir

# Install carbon
cd $stage_dir
echo "checking out carbon $carbon_version"
git clone git://github.com/graphite-project/carbon.git
cd carbon
git reset --hard $carbon_version

echo "installing carbon"
$python setup.py install --prefix=$graphite_install_dir --install-lib=$graphite_install_dir

# Install graphite
cd $stage_dir
echo "checking out graphite-web $graphite_version"
git clone git://github.com/graphite-project/graphite-web.git
cd graphite-web
git reset --hard $graphite_version

echo "installing graphite-web"
python setup.py install --prefix=$graphite_install_dir --install-lib=$graphite_install_dir

# Clean up
if [ ! -d "$HOME/data" ] ; then
  echo "moving data directories into place"
  mv $graphite_install_dir/storage $HOME/data
fi

mv $PROJECT_ROOT/conf/graphite_local_settings.py $graphite_install_dir/graphite/local_settings.py
mv $PROJECT_ROOT/conf/* $graphite_install_dir/conf

cat >> /app/conf/environment.conf << EOF
export PATH="$graphite_install_dir/bin:$PATH"
export PYTHONPATH="$graphite_install_dir:$graphite_install_dir/lib:$PYTHONPATH"
export GRAPHITE_STORAGE_DIR="$HOME/data"
EOF
