#!/bin/bash
graphite_install_dir="$HOME/graphite"
graphite_version="origin/0.9.10"
carbon_install_dir="$HOME/carbon"
carbon_version="origin/0.9.10"

# Install carbon
echo "checking out carbon $carbon_version"
git clone git://github.com/graphite-project/carbon.git
cd carbon
git reset --hard $carbon_version

echo "installing carbon"
python setup.py install --prefix=$graphite_install_dir --install-lib=$graphite_install_dir
cd ~

# Install graphite
echo "checking out graphite-web $graphite_version"
git clone git://github.com/graphite-project/graphite-web.git
cd graphite-web
git reset --hard $graphite_version

echo "installing graphite-web"
python setup.py install --prefix=$graphite_install_dir --install-lib=$graphite_install_dir

# Clean up
if [ ! -d "$HOME/data" ] ; then
  echo "moving data directories into place"
  mv $graphite_install_dir/storage $HOME/data
fi

mv $PROJECT_ROOT/conf/graphite_local_settings.py $graphite_install_dir/graphite/local_settings.py
mv $PROJECT_ROOT/conf/* $graphite_install_dir/conf
